spring.application.name=api-ai
spring.ai.openai.base-url=https://ollama.com
spring.ai.openai.api-key=${OLLAMA_API_KEY}
spring.ai.openai.chat.options.model=qwen3-coder:480b

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.ai.chat.memory=DEBUG
logging.level.org.springframework.ai.chat.memory.repository.jdbc=DEBUG


#nao inicializa o schema
spring.ai.chat.memory.repository.jdbc.initialize-schema=never

#VEJA OS LOGS
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#Conexao do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

#Conexao do MySQL 
#spring.datasource.url=jdbc:mysql://localhost:3310/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=myuser
#spring.datasource.password=secret
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#Configuraco do JPA/HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true