spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.model=${MODEL_NAME:llama-3.3-70b-versatile}

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.ai.chat.memory=DEBUG
logging.level.org.springframework.ai.chat.memory.repository.jdbc=DEBUG


#nao inicializa o schema
spring.ai.chat.memory.repository.jdbc.initialize-schema=never

#VEJA OS LOGS
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#Conexao do PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
#spring.datasource.username=myuser
#spring.datasource.password=secret
#spring.datasource.driver-class-name=org.postgresql.Driver

#Conexao do PostgreSQL Hospedado
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Conexao do MySQL 
#spring.datasource.url=jdbc:mysql://localhost:3310/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=myuser
#spring.datasource.password=secret
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#Configuraco do JPA/HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true